Repository ripe-tech/ripe-sdk-components-vue, pull requests merged in 2020-08, with the labels that each got.

#15 #2: Configurator Component Enhanced
  README.md
  res/images/configurator-sensitivity.gif
  vue/components/organisms/ripe-configurator/ripe-configurator.stories.js
  vue/components/organisms/ripe-configurator/ripe-configurator.vue
Labels: documentation, enhancement, unit-testing

#17 Fix parseFrameKey import
  vue/components/organisms/ripe-configurator/ripe-configurator.vue
Labels: bug

#16 #3: Image Component Enhanced
  README.md
  res/images/image-personalization.png
  vue/components/organisms/ripe-image/ripe-image.stories.js
  vue/components/organisms/ripe-image/ripe-image.vue
Labels: documentation, enhancement, unit-testing

#20 Parts bidirectionality and refactor
  vue/components/organisms/ripe-configurator/ripe-configurator.vue
  vue/components/organisms/ripe-image/ripe-image.vue
  vue/components/organisms/ripe-pickers/ripe-pickers.vue
  vue/components/organisms/ripe-price/ripe-price.vue
  vue/mixins/index.js
  vue/mixins/logic.js
Labels: enhancement

#21 Use set parts instead of config
  vue/components/organisms/ripe-configurator/ripe-configurator.vue
  vue/components/organisms/ripe-image/ripe-image.vue
  vue/components/organisms/ripe-price/ripe-price.vue
  vue/mixins/logic.js
Labels: enhancement

#19 Add Styleguidist for docs
  .github/workflows/main.yml
  .storybook/manager-head.html
  package.json
  styleguide.config.js
  vercel.json
Labels: enhancement

#22 Remove dependency on UXF Webpack
  package.json
  vue/mixins/logic.js
  vue/test/webpack.config.js
  webpack.config.js
Labels: enhancement
