Repository ripe-tech/ripe-sdk-components-vue, pull requests merged in 2020-11, with the labels that each got.

#32 Optional config
  package.json
  vue/components/organisms/ripe-configurator/ripe-configurator.vue
  vue/components/organisms/ripe-image/ripe-image.vue
  vue/components/organisms/ripe-price/ripe-price.vue
  vue/mixins/logic.js
Labels: enhancement

#34 Fixed removed config condition
  vue/components/organisms/ripe-configurator/ripe-configurator.vue
  vue/components/organisms/ripe-image/ripe-image.vue
  vue/components/organisms/ripe-price/ripe-price.vue
Labels: bug

#37 Update docs with recent changes
  doc/overview.md
  vue/components/organisms/ripe-configurator/ripe-configurator.vue
  vue/components/organisms/ripe-price/ripe-price.vue
Labels: documentation, enhancement

#35 Storybook route
  package.json
  styleguide.config.js
  vercel.json
Labels: bug

#36 Tests for ripe-pickers
  vue/components/organisms/ripe-pickers/ripe-pickers.vue
  vue/test/components/ripe-pickers/ripe-pickers.test.js
  vue/test/mocks/index.js
  vue/test/mocks/ripe.js
Labels: unit-testing

#29 #26: Image component with Zoom
  doc/overview.md
  res/images/image-zoom.png
  vue/components/organisms/index.js
  vue/components/organisms/ripe-image-zoom/ripe-image-zoom.stories.js
  vue/components/organisms/ripe-image-zoom/ripe-image-zoom.vue
  vue/components/organisms/ripe-image/ripe-image.vue
  vue/test/components/ripe-image-zoom/ripe-image-zoom.test.js
Labels: enhancement

#38 #172 Support for image extra options
  doc/overview.md
  vue/components/organisms/ripe-configurator/ripe-configurator.vue
  vue/components/organisms/ripe-image/ripe-image.vue
  vue/components/organisms/ripe-price/ripe-price.vue
  vue/mixins/logic.js
Labels: back-port 🔮, documentation, enhancement
