Repository ripe-tech/ripe-sdk-components-vue, pull requests merged in 2021-02, with the labels that each got.

#51 #28 Remove workflow for node 11
  .github/workflows/main.yml
  .travis.yml
Labels: bug

#52 Fix storybook component search
  vue/components/organisms/interaction-structure.stories.js
  vue/components/organisms/interaction.stories.js
  vue/components/organisms/ripe-configurator/ripe-configurator.stories.js
  vue/components/organisms/ripe-image-zoom-hover/ripe-image-zoom-hover.stories.js
  vue/components/organisms/ripe-image-zoom/ripe-image-zoom.stories.js
  vue/components/organisms/ripe-image/ripe-image.stories.js
  vue/components/organisms/ripe-pickers/ripe-pickers.stories.js
  vue/components/organisms/ripe-price/ripe-price.stories.js
Labels: back-port 🔮, bug, enhancement

#53 feat: ripe-image emit loaded and error events
  vue/components/organisms/ripe-configurator/ripe-configurator.vue
  vue/components/organisms/ripe-image/ripe-image.vue
Labels: back-port 🔮, enhancement
