Repository ripe-tech/ripe-sdk-components-vue, pull requests merged in 2021-01, with the labels that each got.

#46 Fixed storybook not being in fullscreen
  .storybook/preview.js
Labels: bug

#47 chore: rename now to vercel
  package.json
  vercel.json
Labels: enhancement

#43 Move RIPE instance-related logic to mixin
  doc/overview.md
  package.json
  vue/components/organisms/interaction-structure.stories.js
  vue/components/organisms/interaction.stories.js
  vue/components/organisms/ripe-configurator/ripe-configurator.stories.js
  vue/components/organisms/ripe-configurator/ripe-configurator.vue
  vue/components/organisms/ripe-image-zoom-hover/ripe-image-zoom-hover.stories.js
  vue/components/organisms/ripe-image-zoom-hover/ripe-image-zoom-hover.vue
  vue/components/organisms/ripe-image-zoom/ripe-image-zoom.stories.js
  vue/components/organisms/ripe-image/ripe-image.stories.js
  vue/components/organisms/ripe-image/ripe-image.vue
  vue/components/organisms/ripe-pickers/ripe-pickers.vue
  vue/components/organisms/ripe-price/ripe-price.stories.js
  vue/components/organisms/ripe-price/ripe-price.vue
  vue/mixins/logic.js
  vue/test/components/ripe-pickers/ripe-pickers.test.js
  vue/test/setup.js
Labels: back-port 🔮, enhancement, risky ❕, talk

#48 fix: shouldReset logic fix
  vue/mixins/logic.js
Labels: bug

#49 #2 Add configuring and price Vue emits
  vue/components/organisms/ripe-price/ripe-price.vue
  vue/mixins/logic.js
Labels: enhancement

#50 fix: remove unnecessary state update
  vue/components/organisms/ripe-image/ripe-image.vue
Labels: bug
